"""initial_schemas

Revision ID: 024c6c427fc6
Revises: 
Create Date: 2026-07-18 17:48:48.268260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024c6c427fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    op.create_table('endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('HTTP', 'HTTPS', name='endpoint_type'), nullable=False),
    sa.Column('status', sa.Enum('UP', 'DOWN', 'DEGRADED', 'UNKNOWN', name='endpoint_status'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('method', sa.Enum('GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', name='http_method'), nullable=False),
    sa.Column('response_time', sa.Integer(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('uptime', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'url'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_endpoints_group_id'), 'endpoints', ['group_id'], unique=False)
    op.create_table('histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('latency', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Float(), nullable=False),
    sa.Column('error', sa.Integer(), nullable=False),
    sa.Column('check_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_endpoint_id'), 'histories', ['endpoint_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_at_status_code', sa.Integer(), nullable=False),
    sa.Column('ended_at_status_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_endpoint_id'), 'incidents', ['endpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_endpoint_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_histories_endpoint_id'), table_name='histories')
    op.drop_table('histories')
    op.drop_index(op.f('ix_endpoints_group_id'), table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
