"""add UNKNOWN to endpoint status enum and new model for incident

Revision ID: 4b7410f5e197
Revises: e705bb1f20c5
Create Date: 2026-07-18 13:39:28.761688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b7410f5e197'
down_revision: Union[str, Sequence[str], None] = 'e705bb1f20c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('occurred_at_status_code', sa.Integer(), nullable=False))
    op.add_column('incidents', sa.Column('ended_at_status_code', sa.Integer(), nullable=True))
    op.alter_column('incidents', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('incidents', 'status_code')
    op.drop_column('incidents', 'status')
    op.drop_column('incidents', 'endpoint_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('endpoint_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('incidents', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('incidents', 'ended_at_status_code')
    op.drop_column('incidents', 'occurred_at_status_code')
    op.drop_column('incidents', 'ended_at')
    # ### end Alembic commands ###
