"""add UNKNOWN to endpoint status enum

Revision ID: e705bb1f20c5
Revises: 70b123bda8af
Create Date: 2026-07-17 11:56:30.171855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e705bb1f20c5'
down_revision: Union[str, Sequence[str], None] = '70b123bda8af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE endpoint_status ADD VALUE 'UNKNOWN'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
